# Generated by Django 6.0.2 on 2026-03-01 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('established_year', models.IntegerField(blank=True, null=True)),
                ('university_affiliation', models.CharField(blank=True, max_length=255, null=True)),
                ('is_government_or_private', models.CharField(choices=[('Government', 'Government'), ('Private', 'Private'), ('Aided', 'Aided')], max_length=50)),
                ('website_url', models.URLField(blank=True, max_length=500, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('has_hostel', models.BooleanField(default=False)),
                ('has_wifi', models.BooleanField(default=False)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=200)),
                ('degree_level', models.CharField(max_length=50)),
                ('stream', models.CharField(max_length=100)),
                ('duration_years', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CollegeCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_seats_available', models.IntegerField(blank=True, null=True)),
                ('entrance_exam_required', models.CharField(blank=True, max_length=100, null=True)),
                ('tuition_fee', models.IntegerField(help_text='Per year tuition fee')),
                ('hostel_fee', models.IntegerField(blank=True, help_text='Per year hostel fee', null=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offered_courses', to='colleges.college')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colleges_offering', to='colleges.course')),
            ],
        ),
    ]
