# Generated by Django 6.0.2 on 2026-03-04 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0002_college_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accreditation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_name', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['body_name', 'grade'],
            },
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EntranceExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Facilities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(db_index=True, max_length=200)),
                ('average_salary_range', models.CharField(blank=True, max_length=150, null=True)),
                ('industry_demand_level', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['job_title'],
            },
        ),
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('highest_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('placement_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='0-100 percentage', max_digits=5, null=True)),
                ('major_recruiters', models.TextField(blank=True, help_text='Comma-separated company names', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-placement_percentage'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['skill_name'],
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StudentReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_score', models.DecimalField(db_index=True, decimal_places=1, default=0.0, help_text='Overall rating', max_digits=3)),
                ('rating_faculty', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('rating_placement', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('rating_infrastructure', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('rating_campus_life', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('review_text', models.TextField(default='')),
                ('reviewer_role', models.CharField(choices=[('Student', 'Student'), ('Alumni', 'Alumni')], default='Student', max_length=50)),
                ('year_of_study_or_graduation', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('established_year', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Universities',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='college',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='collegecourse',
            options={'ordering': ['college__name', 'course__degree__name']},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['degree__name', 'specialization__name']},
        ),
        migrations.RemoveField(
            model_name='college',
            name='description',
        ),
        migrations.RemoveField(
            model_name='college',
            name='has_hostel',
        ),
        migrations.RemoveField(
            model_name='college',
            name='has_wifi',
        ),
        migrations.RemoveField(
            model_name='college',
            name='is_government_or_private',
        ),
        migrations.RemoveField(
            model_name='college',
            name='location',
        ),
        migrations.RemoveField(
            model_name='college',
            name='university_affiliation',
        ),
        migrations.AlterUniqueTogether(
            name='collegecourse',
            unique_together={('college', 'course')},
        ),
        migrations.AddField(
            model_name='college',
            name='city',
            field=models.CharField(db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='college',
            name='country',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='college',
            name='district',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='ownership_type',
            field=models.CharField(choices=[('Government', 'Government'), ('Private', 'Private'), ('Aided', 'Aided')], db_index=True, default='Private', max_length=50),
        ),
        migrations.AddField(
            model_name='college',
            name='state',
            field=models.CharField(db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='collegecourse',
            name='average_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='collegecourse',
            name='course_duration',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Duration in years', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='collegecourse',
            name='cutoff_rank',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='collegecourse',
            name='entrance_exam_requirements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collegecourse',
            name='highest_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='collegecourse',
            name='placement_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='0-100 percentage', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='collegecourse',
            name='seat_intake',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='college',
            name='rating',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='collegecourse',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offered_courses', to='colleges.college'),
        ),
        migrations.AlterField(
            model_name='collegecourse',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='colleges_offering', to='colleges.course'),
        ),
        migrations.AlterField(
            model_name='collegecourse',
            name='hostel_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Per year hostel fee', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='collegecourse',
            name='tuition_fee',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0.0, help_text='Per year tuition fee', max_digits=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration_years',
            field=models.DecimalField(decimal_places=1, default=4.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='college',
            name='accreditations',
            field=models.ManyToManyField(blank=True, related_name='colleges', to='colleges.accreditation'),
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career_name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('industry_sector', models.CharField(blank=True, max_length=200, null=True)),
                ('average_salary_range', models.CharField(blank=True, max_length=150, null=True)),
                ('demand_growth_rate', models.CharField(blank=True, max_length=100, null=True)),
                ('future_outlook', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courses', models.ManyToManyField(blank=True, related_name='careers', to='colleges.course')),
            ],
            options={
                'ordering': ['career_name'],
            },
        ),
        migrations.CreateModel(
            name='CollegeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='colleges/images/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='colleges.college')),
            ],
            options={
                'ordering': ['-is_primary', 'id'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='degree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='colleges.degree'),
        ),
        migrations.AddField(
            model_name='collegecourse',
            name='entrance_exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='required_for_courses', to='colleges.entranceexam'),
        ),
        migrations.AddIndex(
            model_name='collegecourse',
            index=models.Index(fields=['tuition_fee'], name='colleges_co_tuition_2c45d3_idx'),
        ),
        migrations.AddField(
            model_name='college',
            name='facilities',
            field=models.ManyToManyField(blank=True, related_name='colleges', to='colleges.facility'),
        ),
        migrations.AddField(
            model_name='job',
            name='associated_career',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='colleges.career'),
        ),
        migrations.AddField(
            model_name='placement',
            name='college_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='colleges.collegecourse'),
        ),
        migrations.AddField(
            model_name='career',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='careers', to='colleges.skill'),
        ),
        migrations.AlterField(
            model_name='course',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='colleges.specialization'),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('degree', 'specialization')},
        ),
        migrations.AddField(
            model_name='specialization',
            name='stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specializations', to='colleges.stream'),
        ),
        migrations.AddField(
            model_name='studentreview',
            name='college_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='colleges.college'),
        ),
        migrations.AddField(
            model_name='studentreview',
            name='course_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='colleges.course'),
        ),
        migrations.AddField(
            model_name='college',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colleges', to='colleges.university'),
        ),
        migrations.AddIndex(
            model_name='college',
            index=models.Index(fields=['name'], name='colleges_co_name_4cf9c9_idx'),
        ),
        migrations.AddIndex(
            model_name='college',
            index=models.Index(fields=['state'], name='colleges_co_state_06f392_idx'),
        ),
        migrations.RemoveField(
            model_name='collegecourse',
            name='entrance_exam_required',
        ),
        migrations.RemoveField(
            model_name='collegecourse',
            name='total_seats_available',
        ),
        migrations.RemoveField(
            model_name='course',
            name='degree_level',
        ),
        migrations.RemoveField(
            model_name='course',
            name='name',
        ),
        migrations.RemoveField(
            model_name='course',
            name='stream',
        ),
    ]
