# Generated by Django 6.0.2 on 2026-03-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0003_accreditation_degree_entranceexam_facility_job_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='aicte_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='collegecourse',
            name='aicte_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
