# Generated by Django 6.0.2 on 2026-03-15 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0004_college_aicte_id_collegecourse_aicte_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AddIndex(
            model_name='college',
            index=models.Index(fields=['status'], name='colleges_co_status_5fc1f9_idx'),
        ),
    ]
