# Generated by Django 6.0.2 on 2026-03-17 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0006_set_existing_colleges_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload the college logo here.', null=True, upload_to='colleges/logos/'),
        ),
    ]
