# Generated by Django 6.0.2 on 2026-03-17 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0007_college_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(help_text='Enter the full YouTube video URL', max_length=500)),
                ('title', models.CharField(blank=True, help_text='Optional title for the video', max_length=255, null=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='colleges.college')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
