"""
Django settings for pathup_backend project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration
from sentry_sdk.integrations.celery import CeleryIntegration
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+%_o)s!!542i!il5#z5d574qa&@ug8eb)y!ubdgfw(s-rkpf_r'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'pathup_backend.apps.PathUpAdminConfig',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'django_filters',
    'corsheaders',
    'colleges',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pathup_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pathup_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'pathup_db',
        'USER': 'root',
        'PASSWORD': '2006',
        'HOST': 'localhost',
    }
}

CACHE_TTL = 60 * 60  # 1 hour

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",
        "KEY_PREFIX": "pathup",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "CONNECTION_POOL_KWARGS": {"max_connections": 100},
            "IGNORE_EXCEPTIONS": True,
            "COMPRESSOR": "django_redis.compressors.zlib.ZlibCompressor",
        }
    }
}

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173", # Vite React default
    "http://127.0.0.1:5173",
]
CORS_ALLOW_ALL_ORIGINS = True # Enable during dev to avoid React fetch blocks


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Media files (Uploaded Logos, College Images)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Meilisearch Settings
MEILISEARCH_URL = os.environ.get('MEILISEARCH_URL', 'http://127.0.0.1:7700')
MEILISEARCH_MASTER_KEY = os.environ.get('MEILISEARCH_MASTER_KEY', 'default_key')

# Celery Settings
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://127.0.0.1:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'redis://127.0.0.1:6379/2')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'

# Celery Worker Safety Controls
CELERY_TASK_SOFT_TIME_LIMIT = 120
CELERY_TASK_TIME_LIMIT = 300
CELERY_WORKER_MAX_TASKS_PER_CHILD = 100
CELERY_WORKER_CONCURRENCY = 4
CELERY_TASK_ACKS_LATE = True

# Queue Management
CELERY_TASK_ROUTES = {
    'colleges.tasks.*': {'queue': 'search_indexing'},
}

from celery.schedules import crontab

# Periodic Task Scheduling (Celery Beat)
CELERY_BEAT_SCHEDULE = {
    'update-trending-rankings': {
        'task': 'colleges.tasks.calculate_trending_scores',
        'schedule': crontab(minute=0, hour='*/6'), # Every 6 hours
        'options': {'queue': 'search_indexing'}
    },
    'precompute-seo-aggregates': {
        'task': 'colleges.tasks.precompute_seo_aggregates',
        'schedule': crontab(minute=30, hour='*/6'), # Every 6 hours (offset by 30 mins)
        'options': {'queue': 'search_indexing'}
    },
}

# Global DRF Throttles
REST_FRAMEWORK = {
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/day',
        'user': '1000/day'
    }
}

# Sentry Monitoring
if os.environ.get("SENTRY_DSN"):
    sentry_sdk.init(
        dsn=os.environ.get("SENTRY_DSN"),
        integrations=[
            DjangoIntegration(),
            CeleryIntegration(),
        ],
        traces_sample_rate=1.0,
        send_default_pii=True,
        enable_tracing=True,
    )

# Structured JSON Logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'celery_json': {
            'format': '{"time": "%(asctime)s", "level": "%(levelname)s", "name": "%(name)s", "message": "%(message)s"}',
        },
    },
    'handlers': {
        'console_json': {
            'class': 'logging.StreamHandler',
            'formatter': 'celery_json',
        },
    },
    'loggers': {
        'celery.task': {
            'handlers': ['console_json'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}

# ─── Jazzmin Admin Theme ──────────────────────────────────────────────────────
JAZZMIN_SETTINGS = {
    # Window / Tab title
    "site_title": "PathUp Admin",
    # Brand text in the top-left corner
    "site_header": "PathUp College Manager",
    # Brand text on the login page
    "site_brand": "PathUp",
    # Welcome text on the login screen
    "welcome_sign": "Welcome to the PathUp Data Management System",
    # Copyright on the footer
    "copyright": "PathUp Education Platform",
    # Logo
    "site_logo": "img/pathup_logo.png",
    "login_logo": "img/pathup_logo.png",
    "site_logo_classes": "img-circle",
    "site_icon": "img/pathup_logo.png",
    # Top Navigation
    "topmenu_links": [
        {"name": "🏠 Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "🩺 API Health", "url": "/api/health/", "new_window": True},
        {"name": "🌐 Website", "url": "http://localhost:3000", "new_window": True},
    ],
    # Sidebar
    "show_sidebar": True,
    "navigation_expanded": True,
    "order_with_respect_to": [
        "auth",
        "College Core Data",
        "Academic Structure",
        "Admissions & Career",
        "Campus & Facilities",
        "Media & Reviews",
    ],
    # Icons (FontAwesome 5)
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "colleges.College": "fas fa-university",
        "colleges.Course": "fas fa-book",
        "colleges.CollegeCourse": "fas fa-graduation-cap",
        "colleges.Career": "fas fa-briefcase",
        "colleges.Skill": "fas fa-cogs",
        "colleges.University": "fas fa-building",
        "colleges.Stream": "fas fa-stream",
        "colleges.Specialization": "fas fa-microscope",
        "colleges.Degree": "fas fa-scroll",
        "colleges.EntranceExam": "fas fa-file-alt",
        "colleges.Facility": "fas fa-tools",
        "colleges.Accreditation": "fas fa-award",
        "colleges.CollegeImage": "fas fa-image",
        "colleges.Job": "fas fa-id-badge",
        "colleges.Placement": "fas fa-chart-line",
        "colleges.StudentReview": "fas fa-star",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    # Form layout
    "changeform_format": "horizontal_tabs",
    "related_modal_active": True,
    # Custom CSS
    "custom_css": "css/admin_custom.css",
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-dark",
    "accent": "accent-primary",
    "navbar": "navbar-dark",
    "no_navbar_border": True,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "darkly",
    "dark_mode_theme": "darkly",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-outline-light",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
}
